# Generated by Django 4.2.17 on 2025-01-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0002_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("view_user_list", "Can view user list"),
                    ("manage_roles", "Can manage roles"),
                    ("manage_permissions", "Can manage permissions"),
                ]
            },
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this role.",
                related_name="roles",
                to="auth.permission",
                verbose_name="permissions",
            ),
        ),
    ]
