# Generated by Django 4.2.17 on 2025-01-02 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0003_alter_customuser_options_role_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
    ]
