# Generated by Django 4.2.17 on 2025-01-02 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_permission_alter_role_name_alter_userrole_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={"ordering": ["codename"]},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={"ordering": ["user", "role"]},
        ),
    ]
