# Generated by Django 4.2.17 on 2025-01-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_documentimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="edited_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
