# Generated by Django 4.2.17 on 2025-01-15 06:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_remove_document_edited_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="dingtalk_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="dingtalk_unionid",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="dingtalk_userid",
        ),
    ]
